# Pipeline para desplegar Zipkin en Kubernetes de Azure
# Trigger: Manual
# Parámetros: environment (dev, stage, prod, all)

trigger: none  # Solo trigger manual

parameters:
  - name: environment
    displayName: 'Ambiente de despliegue'
    type: string
    default: 'dev'
    values:
      - dev
      - stage
      - prod
      - all

variables:
  - group: k8s-config  # Variable group con configuración de K8s
  serviceConnection: 'Azure-Kubernetes-Service'  # Service connection name

stages:
- stage: DeployZipkin
  displayName: 'Desplegar Zipkin'
  jobs:
  - job: Deploy
    displayName: 'Desplegar Zipkin en Kubernetes'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    
    - task: Bash@3
      displayName: 'Instalar envsubst y Azure CLI'
      inputs:
        targetType: 'inline'
        script: |
          sudo apt-get update
          sudo apt-get install -y gettext-base
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - task: AzureCLI@2
      displayName: 'Login a Azure'
      inputs:
        azureSubscription: '$(serviceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Conectado a Azure"

    - task: Bash@3
      displayName: 'Aplicar manifests de Zipkin'
      inputs:
        targetType: 'inline'
        script: |
          ENVIRONMENTS="${{ parameters.environment }}"
          
          if [ "$ENVIRONMENTS" = "all" ]; then
            ENVIRONMENTS="dev stage prod"
          fi
          
          for env in $ENVIRONMENTS; do
            echo "Desplegando Zipkin en ambiente: $env"
            
            # Obtener variables según el ambiente
            RESOURCE_GROUP_VAR="resourceGroup_${env}"
            CLUSTER_NAME_VAR="aksClusterName_${env}"
            
            # En Azure DevOps, las variables se acceden con $(variableName)
            # Necesitamos usar una técnica diferente
            if [ "$env" = "dev" ]; then
              RESOURCE_GROUP="$(resourceGroup_dev)"
              CLUSTER_NAME="$(aksClusterName_dev)"
            elif [ "$env" = "stage" ]; then
              RESOURCE_GROUP="$(resourceGroup_stage)"
              CLUSTER_NAME="$(aksClusterName_stage)"
            elif [ "$env" = "prod" ]; then
              RESOURCE_GROUP="$(resourceGroup_prod)"
              CLUSTER_NAME="$(aksClusterName_prod)"
            fi
            
            if [ -z "$RESOURCE_GROUP" ] || [ -z "$CLUSTER_NAME" ]; then
              echo "ERROR: Variables no configuradas para el ambiente $env"
              echo "RESOURCE_GROUP: $RESOURCE_GROUP"
              echo "CLUSTER_NAME: $CLUSTER_NAME"
              exit 1
            fi
            
            echo "Conectando al cluster $CLUSTER_NAME en resource group $RESOURCE_GROUP"
            az aks get-credentials \
              --resource-group "$RESOURCE_GROUP" \
              --name "$CLUSTER_NAME" \
              --overwrite-existing
            
            # Crear namespace si no existe
            kubectl create namespace $env --dry-run=client -o yaml | kubectl apply -f -
            
            # Aplicar manifests con substitución de variables
            export NAMESPACE=$env
            envsubst < k8s/zipkin/deployment.yaml | kubectl apply -f -
            envsubst < k8s/zipkin/service.yaml | kubectl apply -f -
            
            echo "Zipkin desplegado exitosamente en $env"
          done

    - task: Bash@3
      displayName: 'Verificar despliegue'
      inputs:
        targetType: 'inline'
        script: |
          ENVIRONMENTS="${{ parameters.environment }}"
          
          if [ "$ENVIRONMENTS" = "all" ]; then
            ENVIRONMENTS="dev stage prod"
          fi
          
          for env in $ENVIRONMENTS; do
            echo "Verificando despliegue en ambiente: $env"
            
            # Obtener variables según el ambiente
            if [ "$env" = "dev" ]; then
              RESOURCE_GROUP="$(resourceGroup_dev)"
              CLUSTER_NAME="$(aksClusterName_dev)"
            elif [ "$env" = "stage" ]; then
              RESOURCE_GROUP="$(resourceGroup_stage)"
              CLUSTER_NAME="$(aksClusterName_stage)"
            elif [ "$env" = "prod" ]; then
              RESOURCE_GROUP="$(resourceGroup_prod)"
              CLUSTER_NAME="$(aksClusterName_prod)"
            fi
            
            az aks get-credentials \
              --resource-group "$RESOURCE_GROUP" \
              --name "$CLUSTER_NAME" \
              --overwrite-existing
            
            kubectl get deployment zipkin -n $env
            kubectl get service zipkin -n $env
            kubectl rollout status deployment/zipkin -n $env --timeout=300s
          done

